# Document:
# http://simiki.org/docs/configuration.html

url: http://yecharles.com 
title: My Wiki
keywords: My Wiki
description: My Wiki 
author: Chang Ye
theme: simple2

deploy:
    - type: git
      remote: origin
      branch: gh-pages 
